[VRTS]
LynxType = "77.000000"
;模拟器类型 24G&77G
CenterFreq = "78.000000"
;模拟器中心频率:GHz
BandWidth = "4.000000"
;模拟器实时带宽:GHz
ERIPTX = "10.000000"
;模拟器接收信号的量程:dBm
SetupDistance = "2.200000"
;模拟器到雷达的中心距离:m

[TXP]
RecordLength = "0.001000"
;数据记录长度:ms 
Trigger = "3.000000"
;Trigger触发类型:[0 "Ref Dig"], [1  "Ref SW"], [2  "Ref IQ"], [3  "None"]
Level = "-60.000000"
;测量信号触发的阀值:dBm

[OBW]
RecordLength = "0.001000"
;数据记录长度:ms
AverageCount = "100.000000"
;数据平均次数，1次0.18s
OBWSpan = "1.000000"
;模拟器测量带宽:GHz
OBWPercentage = "99.500000"
;测量带宽内能量百分比% 对应的带宽